export const projectDetails = [
  {
    name: "AlgorIthm Visualization",
    imageSrc: "/images/algo/algo4.png",
    description: `Alogrithm Visualization like Merge Sort , Quick Sort, Selection Sort and Many more. And visual representation  of how binary search works`,
    technologies: ["#React", "#JavaScript", "#HTML", "#CSS"],
    liveDemo: true,
    liveLink: "https://txxasif.github.io/Monster/",
    codeLink: "https://github.com/txxasif/AlgoVisu",
  },
  {
    name: "E-commerce Site ",
    imageSrc: "/images/ecom.png",
    description: `A simple E-com site using React,Redux and Redux Saga and FireBase Authentication . For some reason the site doesn't work on vercel properly`,
    technologies: ["#React", "#JavaScript", "#Redux", "#ReduxSaga"],
    liveDemo: true,
    liveLink: "https://ecom-sand.vercel.app/",
    codeLink: "https://github.com/txxasif/ecom",
  },
  {
    name: "A Mountain View",
    imageSrc: "/images/cgLab.png",
    description: `This is a project i worked on recently for my Computer Graphics course. It was fun working in this project. I learned how i can show graphics using programming. `,
    technologies: ["#C++", "#Glut"],
    liveDemo: true,
    liveLink: "https://github.com/txxasif/cgLabProject",
    codeLink: "https://github.com/txxasif/cgLabProject",
  },
  {
    name: "School Management",
    imageSrc: "/images/school.png",
    description: `A school management project using JavaFX, OOP and JAVA. It was first project using a framework like JavaFX. It was fun learning Java and JavaFX.`,
    technologies: ["#Java", "#JavaFX", "#SQL", "#OOP"],
    liveDemo: false,
    liveLink: "https://github.com/txxasif/cgLabProject",
    codeLink: "https://github.com/txxasif/schoolmanagement",
  },
  {
    name: "School Management",
    imageSrc: "/images/datastruct.png",
    description: `A school management project using C and Data Structure. It was my first project where i  wrote more than 800+ lines of code.`,
    technologies: ["#C", "#DataStructure"],
    liveDemo: false,
    liveLink: "https://github.com/txxasif/cgLabProject",
    codeLink: "https://github.com/txxasif/schoolmanagmentusingC",
  },
];
